basePath: /api
definitions:
  handler.message:
    properties:
      message:
        type: string
    type: object
  handler.user:
    properties:
      email:
        type: string
    type: object
host: ec2-13-209-98-22.ap-northeast-2.compute.amazonaws.com/
info:
  contact: {}
  title: DailyChaCha Sample Swagger API
  version: "1.0"
paths:
  /getlist:
    get:
      consumes:
      - application/json
      description: Get auth test api
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.user'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: Get test list
swagger: "2.0"
