basePath: /api
definitions:
  handler.AppleSignInRequest:
    properties:
      token:
        type: string
    type: object
  handler.CompleteTodayExerciseRequest:
    properties:
      code:
        type: integer
    type: object
  handler.CompleteTodayExerciseResponse:
    properties:
      object:
        $ref: '#/definitions/models.Object'
    type: object
  handler.CreateExerciseDateRequest:
    properties:
      exercise_dates:
        items:
          type: integer
        type: array
    type: object
  handler.GetOnboardingProgressResponse:
    properties:
      progress:
        type: string
    type: object
  handler.GetTodayExerciseResponse:
    properties:
      exercise:
        $ref: '#/definitions/handler.UserExercise'
      is_exercise_completed:
        type: boolean
    type: object
  handler.GetUserLevelResponse:
    properties:
      goal:
        type: string
      level:
        type: integer
    type: object
  handler.GetUserNextExerciseResponse:
    properties:
      continuity_exercise_day:
        type: integer
      exercise_remain_time:
        type: integer
      object_image_url:
        type: string
    type: object
  handler.GetUserResponse:
    properties:
      email:
        type: string
      user_id:
        type: integer
    type: object
  handler.ListExercisedatesResponse:
    properties:
      exercise_dates:
        items:
          $ref: '#/definitions/handler.exerciseDate'
        type: array
      goal:
        $ref: '#/definitions/handler.goal'
      is_all_dates_same_time:
        type: boolean
    type: object
  handler.ListUserObjectsResponse:
    properties:
      backgrounds:
        items:
          $ref: '#/definitions/handler.UserBackground'
        type: array
      character_image_url:
        type: string
      has_broken_object:
        type: boolean
      objects:
        items:
          $ref: '#/definitions/handler.UserObject'
        type: array
    type: object
  handler.SignInResponse:
    properties:
      access_token:
        type: string
      expired_at:
        type: string
    type: object
  handler.SignInUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.UpdateExerciseDateRequest:
    properties:
      exercise_dates:
        items:
          $ref: '#/definitions/handler.exerciseDate'
        type: array
    type: object
  handler.UserBackground:
    properties:
      display_order:
        description: 정렬 순서
        type: integer
      id:
        type: integer
      image_url:
        description: 이미지 URL
        type: string
    type: object
  handler.UserExercise:
    properties:
      exercise_date:
        description: 운동일
        type: string
      exercise_ended_at:
        description: 운동 종료 시간
        type: string
      exercise_started_at:
        description: 운동 시작 시간
        type: string
      user_id:
        description: 사용자 ID
        type: integer
    type: object
  handler.UserObject:
    properties:
      display_order:
        description: 정렬 순서
        type: integer
      id:
        type: integer
      image_url:
        description: 이미지 URL
        type: string
      object_name:
        description: 오브젝트 이름
        type: string
      object_type:
        description: 오브젝트 유형
        type: string
    type: object
  handler.exerciseDate:
    properties:
      exercise_date:
        type: integer
      exercise_time:
        type: integer
    type: object
  handler.goal:
    properties:
      goal:
        type: string
      index:
        type: integer
    type: object
  handler.message:
    properties:
      message:
        type: string
    type: object
  handler.onboardingStatus:
    properties:
      is_onboarding_completed:
        type: boolean
    type: object
  models.Object:
    properties:
      id:
        type: integer
      image_url:
        description: 이미지 URL
        type: string
      object_name:
        description: 오브젝트 이름
        type: string
      object_type:
        description: 오브젝트 유형
        type: string
    type: object
host: ec2-13-209-98-22.ap-northeast-2.compute.amazonaws.com
info:
  contact: {}
  title: DailyChaCha Sample Swagger API
  version: "1.0"
paths:
  /alert:
    post:
      consumes:
      - application/json
      description: 유저의 온보딩 네번째 - 알림설정 완료하는 API입니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 알림설정 완료 API
  /apple-sign-in:
    post:
      consumes:
      - application/json
      description: Token을 받아 access token을 반환합니다.
      parameters:
      - description: 애플로그인 token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/handler.AppleSignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      summary: 애플 로그인 API
  /dates:
    get:
      consumes:
      - application/json
      description: 유저의 온보딩 여부를 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListExercisedatesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 온보딩 운동일정 가져오는 API
    post:
      consumes:
      - application/json
      description: 유저의 온보딩 두번째 - 날짜를 생성하는 API입니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요일
        in: body
        name: Weekday
        required: true
        schema:
          $ref: '#/definitions/handler.CreateExerciseDateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 날짜정하기 생성 API
    put:
      consumes:
      - application/json
      description: 유저의 온보딩 세번째 - 시간을 생성하는 API입니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 습관 일정
        in: body
        name: ExerciseDate
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateExerciseDateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 시간정하기 API
  /exercises/today:
    get:
      consumes:
      - application/json
      description: 유저의 운동 시점을 가져옵니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetTodayExerciseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 유저의 당일 운동정보를 가져오는 API
    post:
      consumes:
      - application/json
      description: 유저의 운동의 시작과 종료 시간을 기록하는 API
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: '요청(1: 운동시작, 2: 운동종료)'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/handler.CompleteTodayExerciseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CompleteTodayExerciseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 당일 운동시작, 종료 API
  /goals:
    get:
      consumes:
      - application/json
      description: 결심하기에서 사용할 목록들을 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.goal'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 결심하기 목록 API
    post:
      consumes:
      - application/json
      description: 유저의 온보딩 첫번째 - 결심을 생성하는 API입니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 결심
        in: body
        name: Goal
        required: true
        schema:
          $ref: '#/definitions/handler.goal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 결심하기 생성 API
  /level:
    get:
      consumes:
      - application/json
      description: 홈에서 사용될 레벨, 목표를 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetUserLevelResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 유저의 레벨정보를 가져오는 API
  /next-exercise:
    get:
      consumes:
      - application/json
      description: 홈에서 사용될 다음 운동정보들을 들을 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetUserNextExerciseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 유저의 다음 운동정보 API
  /objects:
    get:
      consumes:
      - application/json
      description: 홈에서 사용될 배경, 오브젝트 목록들을 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListUserObjectsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 유저의 오브젝트 목록 API
  /progress:
    get:
      consumes:
      - application/json
      description: 유저의 온보딩 진행상황을 반환합니다. 결심하기가 완료됐다면 'date', 날짜정하기를 완료했다면 'time', 시간정하기를
        완료했다면 'alert'을 보냅니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetOnboardingProgressResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 온보딩 진행상황 API
  /sign-in:
    post:
      consumes:
      - application/json
      description: email, password를 받아 access token을 반환합니다.
      parameters:
      - description: 유저 정보
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.SignInUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      summary: 로그인 API
  /sign-up:
    post:
      consumes:
      - application/json
      description: email, password를 받아 가입합니다.
      parameters:
      - description: 유저 정보
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.SignInUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      summary: 회원가입 API
  /status:
    get:
      consumes:
      - application/json
      description: 유저의 온보딩 여부를 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.onboardingStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 온보딩 상태 API
  /user:
    get:
      consumes:
      - application/json
      description: access token을 확인하여 해당 토큰 유저의 이메일과 user id를 반환합니다.
      parameters:
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.message'
      security:
      - ApiKeyAuth: []
      summary: 유저정보를 가져오는 API입니다.
swagger: "2.0"
