name: ci

on:
  - push

jobs:
  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 5

    

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Lint
        uses: golangci/golangci-lint-action@v3
