name: ci

on:
  - push

jobs:
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker run
        run: |
          docker stop dailychacha && docker rm dailychacha && docker rmi dailycahcah:latest
          docker run -d -p 80:1323 --name go_cicd --restart always dailycahcah:latest