// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDates)
	t.Run("ExerciseGoals", testExerciseGoals)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesDelete)
	t.Run("ExerciseGoals", testExerciseGoalsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesQueryDeleteAll)
	t.Run("ExerciseGoals", testExerciseGoalsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesSliceDeleteAll)
	t.Run("ExerciseGoals", testExerciseGoalsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesExists)
	t.Run("ExerciseGoals", testExerciseGoalsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesFind)
	t.Run("ExerciseGoals", testExerciseGoalsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesBind)
	t.Run("ExerciseGoals", testExerciseGoalsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesOne)
	t.Run("ExerciseGoals", testExerciseGoalsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesAll)
	t.Run("ExerciseGoals", testExerciseGoalsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesCount)
	t.Run("ExerciseGoals", testExerciseGoalsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesHooks)
	t.Run("ExerciseGoals", testExerciseGoalsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesInsert)
	t.Run("ExerciseDates", testExerciseDatesInsertWhitelist)
	t.Run("ExerciseGoals", testExerciseGoalsInsert)
	t.Run("ExerciseGoals", testExerciseGoalsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesReload)
	t.Run("ExerciseGoals", testExerciseGoalsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesReloadAll)
	t.Run("ExerciseGoals", testExerciseGoalsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesSelect)
	t.Run("ExerciseGoals", testExerciseGoalsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesUpdate)
	t.Run("ExerciseGoals", testExerciseGoalsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("ExerciseDates", testExerciseDatesSliceUpdateAll)
	t.Run("ExerciseGoals", testExerciseGoalsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
