// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Backgrounds           string
	ExerciseDates         string
	ExerciseGoals         string
	Objects               string
	UserExerciseHistories string
	UserObjects           string
	Users                 string
}{
	Backgrounds:           "backgrounds",
	ExerciseDates:         "exercise_dates",
	ExerciseGoals:         "exercise_goals",
	Objects:               "objects",
	UserExerciseHistories: "user_exercise_histories",
	UserObjects:           "user_objects",
	Users:                 "users",
}
