// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ExerciseDates string
	ExerciseGoals string
	Users         string
}{
	ExerciseDates: "exercise_dates",
	ExerciseGoals: "exercise_goals",
	Users:         "users",
}
