// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testExerciseGoals(t *testing.T) {
	t.Parallel()

	query := ExerciseGoals()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testExerciseGoalsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExerciseGoalsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ExerciseGoals().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExerciseGoalsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ExerciseGoalSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExerciseGoalsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ExerciseGoalExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ExerciseGoal exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ExerciseGoalExists to return true, but got false.")
	}
}

func testExerciseGoalsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	exerciseGoalFound, err := FindExerciseGoal(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if exerciseGoalFound == nil {
		t.Error("want a record, got nil")
	}
}

func testExerciseGoalsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ExerciseGoals().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testExerciseGoalsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ExerciseGoals().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testExerciseGoalsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	exerciseGoalOne := &ExerciseGoal{}
	exerciseGoalTwo := &ExerciseGoal{}
	if err = randomize.Struct(seed, exerciseGoalOne, exerciseGoalDBTypes, false, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}
	if err = randomize.Struct(seed, exerciseGoalTwo, exerciseGoalDBTypes, false, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = exerciseGoalOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = exerciseGoalTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ExerciseGoals().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testExerciseGoalsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	exerciseGoalOne := &ExerciseGoal{}
	exerciseGoalTwo := &ExerciseGoal{}
	if err = randomize.Struct(seed, exerciseGoalOne, exerciseGoalDBTypes, false, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}
	if err = randomize.Struct(seed, exerciseGoalTwo, exerciseGoalDBTypes, false, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = exerciseGoalOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = exerciseGoalTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func exerciseGoalBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func exerciseGoalAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ExerciseGoal) error {
	*o = ExerciseGoal{}
	return nil
}

func testExerciseGoalsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ExerciseGoal{}
	o := &ExerciseGoal{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal object: %s", err)
	}

	AddExerciseGoalHook(boil.BeforeInsertHook, exerciseGoalBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	exerciseGoalBeforeInsertHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.AfterInsertHook, exerciseGoalAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	exerciseGoalAfterInsertHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.AfterSelectHook, exerciseGoalAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	exerciseGoalAfterSelectHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.BeforeUpdateHook, exerciseGoalBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	exerciseGoalBeforeUpdateHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.AfterUpdateHook, exerciseGoalAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	exerciseGoalAfterUpdateHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.BeforeDeleteHook, exerciseGoalBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	exerciseGoalBeforeDeleteHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.AfterDeleteHook, exerciseGoalAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	exerciseGoalAfterDeleteHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.BeforeUpsertHook, exerciseGoalBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	exerciseGoalBeforeUpsertHooks = []ExerciseGoalHook{}

	AddExerciseGoalHook(boil.AfterUpsertHook, exerciseGoalAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	exerciseGoalAfterUpsertHooks = []ExerciseGoalHook{}
}

func testExerciseGoalsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testExerciseGoalsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(exerciseGoalColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testExerciseGoalsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testExerciseGoalsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ExerciseGoalSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testExerciseGoalsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ExerciseGoals().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	exerciseGoalDBTypes = map[string]string{`ID`: `int`, `UserID`: `int`, `ExerciseGoal`: `varchar`}
	_                   = bytes.MinRead
)

func testExerciseGoalsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(exerciseGoalPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(exerciseGoalAllColumns) == len(exerciseGoalPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testExerciseGoalsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(exerciseGoalAllColumns) == len(exerciseGoalPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ExerciseGoal{}
	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, exerciseGoalDBTypes, true, exerciseGoalPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(exerciseGoalAllColumns, exerciseGoalPrimaryKeyColumns) {
		fields = exerciseGoalAllColumns
	} else {
		fields = strmangle.SetComplement(
			exerciseGoalAllColumns,
			exerciseGoalPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ExerciseGoalSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testExerciseGoalsUpsert(t *testing.T) {
	t.Parallel()

	if len(exerciseGoalAllColumns) == len(exerciseGoalPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLExerciseGoalUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ExerciseGoal{}
	if err = randomize.Struct(seed, &o, exerciseGoalDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ExerciseGoal: %s", err)
	}

	count, err := ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, exerciseGoalDBTypes, false, exerciseGoalPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExerciseGoal struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ExerciseGoal: %s", err)
	}

	count, err = ExerciseGoals().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
